---
# ---------------------------------------------------------------------
# all
# ---------------------------------------------------------------------
- name: Update apt source
  hosts: all
  tasks:
    - name: Update apt source
      become: true
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: '(http|mirror)://\S+'
        # replace: 'http://jp.archive.ubuntu.com/ubuntu'
        # replace: 'http://ftp.jaist.ac.jp/pub/Linux/ubuntu/'
        replace: 'mirror://mirrors.ubuntu.com/mirrors.txt'
        # backup: yes
      when: ansible_facts['os_family'] == "Debian"

- name: Setup all hosts
  hosts: all
  gather_facts: true
  become: false
  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        cache_valid_time: 600
        autoremove: true
        upgrade: "safe"
  # roles/ 配下に独自roleを追加したら、以下のように roles: に列挙して有効化してください
  # roles:
  #   - your-role-name
  tasks:
    - name: Install extra package
      become: true
      ansible.builtin.apt:
        pkg:
          - locales-all
          # - btop
          # - inxi
        state: present

