all:
  children:
    frontend:
      hosts:
        jarvis-prxvm-docker-01:
          ansible_host: 10.71.33.194
          ansible_port: 22
    cluster_clients:
      hosts:
        jarvis-prxvm-gw-01:


    ubuntu2604_sudows:
      hosts:
        jarvis-control-01:

  vars:
    # ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_port: 22
