all:
  children:
    bootstrap_required:
      hosts: {}
    provision_ready:
      hosts: {}
    linux:
      hosts:
        sample-node-01:
          ansible_host: 192.0.2.10
          ansible_port: 22
