bootstrap_user: initial-admin

provisioner_name: ansible
provisioner_uid: ""
provisioner_primary_group: sudo
provisioner_primary_group_gid: ""
provisioner_groups: []
provisioner_shell: /bin/bash
provisioner_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ansible"
provisioner_public_key_file: "{{ provisioner_private_key_file }}.pub"
provisioner_passwordless_sudo: true

ssh_connect_timeout: 5

common_packages: []
common_managed_directories: []
